# Generated by Django 4.0.2 on 2022-05-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_mp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('gn', models.CharField(max_length=100)),
                ('gpn', models.CharField(max_length=100)),
                ('vrf', models.CharField(max_length=100)),
                ('mcs', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cfee', models.IntegerField()),
                ('cdetails', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user_mp')),
            ],
        ),
    ]
