# Generated by Django 4.0.2 on 2022-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_stdworks_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdworks_tbl',
            name='assdate',
            field=models.DateField(auto_now=True),
        ),
    ]
