# Generated by Django 4.0.2 on 2022-04-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
                ('url', models.FileField(upload_to='notes')),
                ('crs', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tutorReg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('dpt', models.CharField(max_length=100)),
                ('desi', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='tutorpic')),
            ],
        ),
        migrations.CreateModel(
            name='Works_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.FileField(upload_to='works')),
                ('wt', models.CharField(max_length=100)),
                ('wdt', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=100)),
            ],
        ),
    ]
