# Generated by Django 4.0.2 on 2022-05-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btname', models.CharField(max_length=25)),
                ('stdname', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
