# Generated by Django 4.0.2 on 2022-05-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_live_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Live_class',
        ),
    ]
