# Generated by Django 4.0.2 on 2022-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_delete_live_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_tbl',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='works_tbl',
            name='wdt',
            field=models.DateField(auto_now=True),
        ),
    ]
